# Generated by Django 4.1.3 on 2023-01-28 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_duaration',
            new_name='course_duration',
        ),
    ]
