# Generated by Django 4.1.3 on 2023-01-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0003_students_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='class_room',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_duration',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(related_name='course', to='ApiApplication.courses'),
        ),
        migrations.AlterField(
            model_name='students',
            name='grade',
            field=models.CharField(max_length=100),
        ),
    ]
