# Generated by Django 4.1.3 on 2023-02-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_duration', models.IntegerField(max_length=10)),
                ('class_room', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=20)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='None.jpg', upload_to='Images')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=200)),
                ('grade', models.CharField(max_length=100)),
                ('courses', models.ManyToManyField(related_name='course', to='university.courses')),
            ],
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name', 'age'], name='university__name_9e3069_idx'),
        ),
    ]
