# Generated by Django 4.1.3 on 2023-02-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_image',
            field=models.FileField(default='None.jpg', upload_to='Images'),
        ),
    ]
